# Generated by Django 3.2.12 on 2022-05-04 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourprice',
            name='customertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customertype', to='tours.customertype'),
        ),
    ]
