# Generated by Django 3.2.12 on 2022-05-04 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tourprice_customertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourprice',
            name='customertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='tours.customertype'),
        ),
    ]
