# Generated by Django 3.2.12 on 2022-05-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20220518_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsaction',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsaction',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
