# Generated by Django 3.2.12 on 2022-05-18 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20220518_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsaction',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tours.news'),
        ),
    ]
