# Generated by Django 3.2.12 on 2022-05-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tourprice_customertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourprice',
            name='price',
            field=models.IntegerField(),
        ),
    ]
